name: Update last Needlify posts
on:
  schedule:
    - cron: '14 21 * * *'
    
jobs:
  update-last-needlify-posts:
    name: Update last Needlify posts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '13'
      - name: Install node dependencies
        run: npm install
      - name: Run script that gets latest blog posts
        run: npm run feed
      - name: Git setup
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Git commit README.md file
        run: |
          git add .
          git commit -am "Feat: I (the github action) updated the readme file for you. I hope you like it ❤"
          git push
